Check for `jq` and `fzf` in `pr-list` script
Other scripts check for `fzf`:
- https://github.com/unixorn/fzf-zsh-plugin/blob/671291a0dba1971d5c87a0cdc809711a9b7636fa/bin/fzf-git-checkout#L28-L30
- https://github.com/unixorn/fzf-zsh-plugin/blob/671291a0dba1971d5c87a0cdc809711a9b7636fa/bin/fzf-browse-pods#L41
- https://github.com/unixorn/fzf-zsh-plugin/blob/671291a0dba1971d5c87a0cdc809711a9b7636fa/bin/fzf-vscode#L44-L46

But, this one was not checking `fzf` and `jq`, which is rather unique for this script. So, I've updated the deps list.

diff --git a/bin/pr-list b/bin/pr-list
--- a/bin/pr-list
+++ b/bin/pr-list
@@ -25,8 +25,16 @@ function has() {
   which "$@" > /dev/null 2>&1
 }
 
-if has gh; then
-  gh api --paginate 'repos/:owner/:repo/pulls?state=open' | jq -r '.[] | [.number, .user.login, .title] | @tsv' | fzf
-else
+if ! has gh; then
   fail "Cannot find 'gh' in your PATH"
 fi
+
+if ! has jq; then
+  fail "Cannot find 'jq' in your PATH"
+fi
+
+if ! has fzf; then
+  fail "Cannot find 'fzf' in your PATH"
+fi
+
+gh api --paginate 'repos/:owner/:repo/pulls?state=open' | jq -r '.[] | [.number, .user.login, .title] | @tsv' | fzf
